### ISSUE TITLE
Add crossJoin, innerJoin, leftJoin, rightJoin and fullJoin.

### ISSUE THREAD

**Issue by mahdyaslami** [mahdyaslami/bare-queryable#32]
- [x] Cross Join
- [x] Inner Join: Add `join()`.
- [x] Add `innerJoin()` helper.
- [x] Left Outer Join: Add `leftJoin()`.
- [x] Right Outer Join: Add `rightJoin()`.
- [ ] Full Join: Add `fullJoin()`.
- [ ] Resolve all todos.

**Comment by mahdiaslami** [comment]
Cross join added before.

**Comment by mahdiaslami** [comment]
# Problem

- What should we do to prevent overwriting properties?
- How should we compare two columns with the same name?

## 1. Force using an alias in join.

```js
query(childs)
    .join(parents, 'p')
        .on('parent_id').col.equal('p.id')
    .get()
```

And result is like:

```js
const r = {
    id: 1,
    name: 'foo',
    /* [[OTHER CHILD PROPS]] */

    p: {
        id: 2,
        name: 'bar',
        /* [[OTHER PARENT PROPS]] */
    }
}
```

## 2. Force using an alias for join and query when using join.


```js
query(childs, 'c')
    .join(parents, 'p')
        .on('c.parent_id').col.equal('p.id')
    .get()
```

And result is like:

```js
const r = {
    c: {
        id: 1,
        name: 'foo',
        /* [[OTHER CHILD PROPS]] */
    },
    
    p: {
        id: 2,
        name: 'bar',
        /* [[OTHER PARENT PROPS]] */
    }
}
```

# 3. Implement both ways 1 and 2, And make them optional.

- If a developer does not provide both aliases, overwrite columns with the same name.
- When the column name in the `on()` method is the same as the column name in the `on().col.<condition>()` method then the first column always belongs to the main array. and the second column always belongs to the joined array.

**Comment by mahdiaslami** [comment]
I think this issue is too big and I must separate it into smaller issues that will handle in one sprint.

- [ ] https://github.com/mahdyaslami/bare-queryable/issues/42
- [ ] https://github.com/mahdyaslami/bare-queryable/issues/43
- [ ] https://github.com/mahdyaslami/bare-queryable/issues/44
